import React, { FC, useMemo } from "react"
import GithubSlugger from "github-slugger"
import { PageSidebarLink } from "../PageSidebarLink"
import { ITocItem } from "../../types"
import * as SC from "./styles"

interface ITocProps {
  header: React.ReactNode
  items: ITocItem[]
}

interface ITitle {
  prefix?: string
  title: string
}

function extractTitle(title: string): ITitle {
  const maybePrefix = title.match(/^(\w+\.)/)
  const rest = maybePrefix ? title.replace(maybePrefix[0], "") : title

  return {
    prefix: maybePrefix ? maybePrefix[0] : undefined,
    title: rest,
  }
}

// needs to match the anchors generated by gatsby-remark-auto-headers-improved
// maybe extract logic
function cleanAnchors(items: ITocItem[]): ITocItem[] {
  const slugger = new GithubSlugger()
  slugger.reset()

  const strip = (value: string) => value.replace(/^(\d*\-)(.*)/, "$2")

  return items.map((item) => ({
    ...item,
    link: `#${strip(slugger.slug(item.title))}`,
  }))
}

export const Toc: FC<ITocProps> = ({ header, items }) => {
  const windowGlobal = typeof window !== "undefined" && window

  const cleanedItems = useMemo(() => {
    return cleanAnchors(items)
  }, [items])

  // window is not available on build
  if (!windowGlobal) {
    return null
  }

  const { pathname } = windowGlobal.location
  return (
    <SC.TocWrapper>
      {header}
      {cleanedItems.map((item) => {
        const { prefix, title } = extractTitle(item.title)

        return (
          <SC.TocItem key={item.link} className={`depth-${item.depth}`}>
            {prefix}
            <PageSidebarLink
              href={`${pathname}${item.link}`}
              text={title}
              type="anchor"
            />
          </SC.TocItem>
        )
      })}
    </SC.TocWrapper>
  )
}
